enum ACTION {
    LOG_IN = 'LOG_IN',
    REGISTRATION = 'REGISTRATION',
    CODE_VERIFY = 'CODE_VERIFY',
    GET_TOKEN = 'GET_TOKEN',
    LOG_OUT = 'LOG_OUT',
    GET_USER = 'GET_USER',
    SET_USER = 'SET_USER',
    SHOW_TOP_MESSAGE = 'SHOW_TOP_ MESSAGE',
    SET_LOADING = 'SET_LOADING'
}

export default ACTION
