enum ACTION {
    LOG_IN = 'LOG_IN',
    REGISTRATION = 'REGISTRATION',
    LOG_OUT = 'LOG_OUT',
    SET_USER = 'SET_USER',
    SHOW_TOP_MESSAGE = 'SHOW_TOP_ MESSAGE',
    SET_LOADING = 'SET_LOADING'
}

export default ACTION
